// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnXmJ2qr98czX6WQs9zyHxL4haPoAHVLA',
    appId: '1:103018242086:web:6820f88fbb648940a406e7',
    messagingSenderId: '103018242086',
    projectId: 'chatappmo-f3837',
    authDomain: 'chatappmo-f3837.firebaseapp.com',
    storageBucket: 'chatappmo-f3837.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA7dQgDlNAO2byO5VFwvxbRPpejcCJ5bFQ',
    appId: '1:103018242086:android:7ea2297287935560a406e7',
    messagingSenderId: '103018242086',
    projectId: 'chatappmo-f3837',
    storageBucket: 'chatappmo-f3837.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpFB0wVd-MoDbROXMCmFLM3fXEGHjVFso',
    appId: '1:103018242086:ios:248c73c56fb1bd93a406e7',
    messagingSenderId: '103018242086',
    projectId: 'chatappmo-f3837',
    storageBucket: 'chatappmo-f3837.appspot.com',
    iosBundleId: 'com.example.chatAppMax',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpFB0wVd-MoDbROXMCmFLM3fXEGHjVFso',
    appId: '1:103018242086:ios:248c73c56fb1bd93a406e7',
    messagingSenderId: '103018242086',
    projectId: 'chatappmo-f3837',
    storageBucket: 'chatappmo-f3837.appspot.com',
    iosBundleId: 'com.example.chatAppMax',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDnXmJ2qr98czX6WQs9zyHxL4haPoAHVLA',
    appId: '1:103018242086:web:b02933871743a89da406e7',
    messagingSenderId: '103018242086',
    projectId: 'chatappmo-f3837',
    authDomain: 'chatappmo-f3837.firebaseapp.com',
    storageBucket: 'chatappmo-f3837.appspot.com',
  );
}
